### ISSUE TITLE
First selection of Update Plot uses cohort_id=1

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#101]
When creating a plot in a worksheet, no matter what cohort is selected, when you first click "Update Plot", it uses cohort_id=1

**Comment by phyllers** [comment]
Same on second try. Seems hard coded somewhere.

**Comment by rgbohner** [comment]
addressed in https://github.com/isb-cgc/ISB-CGC-Webapp/pull/90

**Comment by phyllers** [comment]
working
