### ISSUE TITLE
Trying to create Gene List from worksheet has js import errors

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#108]
<img width="959" alt="screen shot 2016-01-22 at 10 04 39 am" src="https://cloud.githubusercontent.com/assets/4040084/12518806/9634f20a-c0ef-11e5-89d9-c134bfaf74e3.png">

I think this is preventing it from getting the autocomplete genes. This is not an issue if you try to create a new gene list from the dashboard.

**Comment by rgbohner** [comment]
Looks like a loading error in the require config at the top of the page.  Causing it not to find the js file. I'll make the fix
