### ISSUE TITLE
_ah/api/feature_data_api/v1/feature_data_plot is very slow

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#110]
Minimal request time is 8 seconds and can take up to several minutes

**Comment by zrodebaugh** [comment]
@rgbohner @kleisb isb-cgc/software-engineering-coordination/issues/991 has been opened to adapt the work done in isb-cgc/software-engineering-coordination/issues/946 and resolve this issue. can you both work together on this? more detail: https://github.com/isb-cgc/ISB-CGC-Webapp/compare/feature/946

**Comment by kleisb** [comment]
isb-cgc/software-engineering-coordination#946 started as work on prototyping ways to speed up the 
 `feature_data_plot` API. 

A short summary of the solution: 
BigQuery jobs are [submitted](https://github.com/isb-cgc/ISB-CGC-Webapp/blob/feature/946/bq_data_access/data_access.py#L159) in asynchronous mode. Query results are unpacked and post-processed as they become available, in a [polling loop](https://github.com/isb-cgc/ISB-CGC-Webapp/blob/feature/946/bq_data_access/data_access.py#L175).
Some big changes done to the BigQuery access module:
- The feature data provider classes are now subclassed from [FeatureDataProvider](https://github.com/isb-cgc/ISB-CGC-Webapp/blob/feature/946/bq_data_access/feature_data_provider.py)
- The base class contains the BigQuery access functions (submitting jobs etc), while the datatype-specific subclasses handle the feature definition parsing, query string construction and query result unpacking
- A [fix for data structure misuse](https://github.com/isb-cgc/ISB-CGC-Webapp/commit/d926c5637634576d5dcc044e12da034ef42bcc24#diff-73eb5afdf6aac5bcf361b8ef69c29ad1) that likely resolves this issue.

https://github.com/isb-cgc/software-engineering-coordination/issues/991 should track work on adapting the `USER` feature type to the work described above.

**Comment by rgbohner** [comment]
@kleisb Would you be willing to give me access to view isb-cgc/software-engineering-coordination#946  and isb-cgc/software-engineering-coordination#991

**Comment by kleisb** [comment]
@rgbohner Those issues (946 and 991) don't have any detailed explanations. 946 is about using asynchronous jobs with BigQuery, and 991 is about adapting the `USER` data type endpoint [user_data.py](https://github.com/isb-cgc/ISB-CGC-Webapp/blob/master/bq_data_access/user_data.py) to the work done in 946.

Here are the commits for issue 946 so far: https://github.com/isb-cgc/ISB-CGC-Webapp/compare/feature/946

Can you confirm whether or not this particular issue is solved (the data structure misuse)? For the `USER` data support in the endpoint, I think we should open a new issue in a repository accessible to all participants, and I'll close 991.

**Comment by rgbohner** [comment]
I think the solution you committed is an improvement but I cannot validate whether this is a solution to the problem.  Over this issue is meant to articulate the concern that querying data for plots takes an exceptionally long time from a user's perspective.  From this, there are steps we need to take.  1. Validate the implementation to gather data from BigQuery is sufficiently optimal for the data set, which I think may have done in the work above.  Have you run query tests to see there were was a drop in query time for different cohort sets?   2.  It might be quite possible that our data size limits our ability to perform on demand plot queries in a reasonable time frame (< 1 min). If that is the case, we need to think of potentially creating a plot rendering mechanism to allow users to submit plots and retrieve them at a later time.

**Comment by kleisb** [comment]
I've been running queries (through the endpoint) as part of the development process related to feature 946. I tested all data types excluding `USER` as part of refactoring the data type specific modules to the new BigQuery logic. The roundtrip time for the endpoint in a local development environment seems to be around 15 seconds, for three features (`x`, `y` and `c`). The bottleneck was not BigQuery itself, but the post-processing of the query results, worst case being the inclusion of the `All TCGA`-cohort.

**Comment by kleisb** [comment]
@rgbohner The changes done in the issue I referred to have been merged to the master branch of [ISB-CGC-Webapp](https://github.com/isb-cgc/ISB-CGC-Webapp), which should by now be deployed to the [`dev`](https://mvm-dot-isb-cgc.appspot.com/) cloud deployment of the web application. Please see if the response time issue has been addressed, given your test cases.

**Comment by rgbohner** [comment]
@kleisb Thanks for the update.  Can you reference merge commit hash in this thread so we can track the code changes to this issue?

**Comment by phyllers** [comment]
https://github.com/isb-cgc/ISB-CGC-Webapp/commit/3631c589c7df2c429ca7d6f49aaf9737aaebf1b9

That's the merged into master commit.

**Comment by rgbohner** [comment]
Cool, this code was part of the merge to LSDF 283f51bd1ee0a507dc33e283be839fb76171224b last night and is deployed on our stage server.   I'll run some tests today to see if the plot latency is still an issue

**Comment by kleisb** [comment]
@rgbohner Did you observe any improvement in the endpoint roundtrip times?
