### ISSUE TITLE
Sample analysis images do not link to creation of new workbooks in dashboard

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#112]

**Comment by rgbohner** [comment]
I need to validate this one with Heidi, she may have had a reason for not doing this

**Comment by rgbohner** [comment]
updating this along with #150

**Comment by rgbohner** [comment]
This issue is a two parter.  The design is intended for each of those images to link to a "sample" workbook that has been preconfigured with interesting analysis.  
In order to enable sample workbooks:
1.  I enabled the admin interface to view the is_public attribute of workbooks.  
2.  A user (admin) can create an interesting analysis in a workbook
3.  the admin can go to the admin interface and change that workbook is_public attribute to true
4.  In the dashboard template page, add a href on the images to the public workbook link (ie domain.com/workbook/<workbook_id)

I cannot finish this task as I have no idea on what an interesting analysis would look like for each one of the plots we have enabled

**Comment by phyllers** [comment]
I also don't know what will be useful. Let's let Brady figure that out and I will work with him to make it linkable from the dashboard.

**Comment by rgbohner** [comment]
we could also be more flexible and adapt the dashboard template to search and load the first public workbook containing each of the plot types.  I would hate to have to hardcode workbook urls into the repo

**Comment by phyllers** [comment]
Yes, I agree.
