### ISSUE TITLE
Gene favourites Count not updated in menu bar

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#116]
![screen shot 2016-01-22 at 5 59 06 pm](https://cloud.githubusercontent.com/assets/4040084/12527534/eff42ea4-c131-11e5-9e44-d7a9255cdcd0.png)

You'll notice that I have a gene list, but it's not reflected in the menu bar

**Comment by rgbohner** [comment]
Similar to #141
