### ISSUE TITLE
When Creating a plot, all fields are required

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#117]
![screen shot 2016-01-22 at 6 17 28 pm](https://cloud.githubusercontent.com/assets/4040084/12527662/6a7ccc60-c134-11e5-98ce-4be5e188d1a3.png)

An error occurs if I try to just select an x-axis. I believe [this](https://github.com/BlinkUX/ISB-CGC/blob/master/static/js/workbooks.js#L236) line creates the attr objects that gets checked [here](https://github.com/BlinkUX/ISB-CGC/blob/master/workbooks/views.py#L428). attrs['x_axis', 'y_axis', 'color_by','cohort'] will always evaluate to true even if the underlying object is undefined.

**Comment by rgbohner** [comment]
We need to adjust the plot setting requirements based on the type of analysis
