### ISSUE TITLE
Able to have duplicate cohorts in worksheet, leads to error in trying to remove one.

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#128]
<img width="597" alt="screen shot 2016-02-05 at 10 56 53 am" src="https://cloud.githubusercontent.com/assets/4040084/12855954/443ebdf6-cbf7-11e5-9555-58338a3f1ed2.png">
<img width="1028" alt="screen shot 2016-02-05 at 10 57 44 am" src="https://cloud.githubusercontent.com/assets/4040084/12855965/50a31628-cbf7-11e5-8481-301ec3acfcce.png">

**Comment by rgbohner** [comment]
We need to check to see if the cohort exists before adding

**Comment by phyllers** [comment]
Good fix!
