### ISSUE TITLE
Cannot Edit and Save Variable List

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#140]
<img width="955" alt="screen shot 2016-02-10 at 1 24 09 pm" src="https://cloud.githubusercontent.com/assets/4040084/12962275/a00ab1a2-cff9-11e5-9e22-76d2d0cf0e35.png">

We get an error when trying to make changes to a variable favourites list.

**Comment by phyllers** [comment]
I've managed to make a small change to fix this the first time, but if I try to edit the same variable list, i get a server error.

To reproduce:
1. Create variable favourite list. Save.
2. Edit list by adding variable. Save.

This leads to a `ValueError: invalid literal for int() with base 10: 'None'`

**Comment by phyllers** [comment]
![screen shot 2016-02-10 at 3 18 21 pm](https://cloud.githubusercontent.com/assets/4040084/12965254/8c2d5d28-d009-11e5-9f0a-dbd0a67556a4.png)

**Comment by rgbohner** [comment]
Error on updating variable list already created

**Comment by phyllers** [comment]
working
