### ISSUE TITLE
Loading bar for plots removed

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#142]
I remember seeing a fancy loading bar maybe last week or the week before. That seems to have disappeared, and I'm not sure if this is related to some other code changes that got merged in, or what.

Also I haven't been able to view any plots and the one that I did manage to get last was a bar chart where all the bars were black. Do you folks happen to have a screenshot of a working plot?

**Comment by phyllers** [comment]
I got my plots working, but I still don't see the fancy loading bar. Is that an lsdf specific feature?

**Comment by rgbohner** [comment]
Its not, err if wasn't intended to be.  I'll hit this issue back up in a few days and copy over the css objects to css that cgc uses

**Comment by phyllers** [comment]
So pretty!
