### ISSUE TITLE
Multiple Cohorts per Plot

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#143]
I just realized that the plots only provide the option to show one cohort per plot, but I had it implemented to allow multiple cohorts per plot. Was this a decision made based on timelines? Can it be put back?

**Comment by rgbohner** [comment]
This was not a conscious decision.  It happened when I implemented a single select ui by mistake. The underlying post code actually requires an array of cohorts as an input, so the only change is converting the ui element from single select to a multi select element.  I'll assign this to myself

**Comment by rgbohner** [comment]
addressed https://github.com/isb-cgc/ISB-CGC-Webapp/pull/90
