### ISSUE TITLE
Cannot view analyses in shared workbooks

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#150]
When looking at a workbook that's shared with you, the plots don't get generated automatically, and there are no options to make changes or regenerate the plot.

![screen shot 2016-02-19 at 1 10 43 pm](https://cloud.githubusercontent.com/assets/4040084/13189087/36afebd8-d70a-11e5-8b05-2b2215814d6f.png)

**Comment by rgbohner** [comment]
Add in a check to see if a ploit model exists then autoplot

**Comment by rgbohner** [comment]
The problem still persists in another scenario fixing now

**Comment by rgbohner** [comment]
the display button is not showing up

**Comment by rgbohner** [comment]
This issue of the display button was a merge error on the LSDF side, the fix should be working fine
