### ISSUE TITLE
Genes are not used on plots

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#153]
@phyllers Can you expand on how this might work better

**Comment by phyllers** [comment]
This screenshot shows how one would select the variable they're interested in.
![screen shot 2016-02-23 at 2 03 19 pm](https://cloud.githubusercontent.com/assets/4040084/13268792/50af7530-da39-11e5-8388-050be9cf3392.png)

This screenshot shows how the variable they selected in the previous screenshot would appear in the plot settings. Where a new select box would appear with the genes that they have as their sources.
![screen shot 2016-02-23 at 2 25 25 pm](https://cloud.githubusercontent.com/assets/4040084/13268791/50af0a14-da39-11e5-8860-e81d5acbe08c.png)

Accomplishing this would require a lot of extra work. Separating the selectable variables from the current feature definitions will be tricky. 

Some data types do not use genes, like methylation. That uses probes which is something that we would not have a filter for outside of the variable selection.

**Comment by phyllers** [comment]
Do you think some form of this could be ready by Monday? I'm trying to understand what's left to do before our release. Thanks!

**Comment by phyllers** [comment]
Looks good. I added a small fix so that the colour_by select box is populated by the selected x and y axis, but also the common variables.
