### ISSUE TITLE
500 error on _ah/api/feature_data_api/v1/feature_data_plot

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#156]
It appears this is an intermittent error

Here is debug log : 

INFO     2016-02-24 19:25:55,641 recording.py:676] Saved; key: **appstats**:055500, part: 83 bytes, full: 6187 bytes, overhead: 0.000 + 0.002; link: http://127.0.0.1:8080/_ah/stats/details?time=1456341955576
INFO     2016-02-24 19:25:55,648 module.py:786] mvm: "POST /workbooks/1/worksheets/1/plots/17/edit HTTP/1.1" 200 22
INFO     2016-02-24 19:25:55,874 module.py:786] mvm: "POST /_ah/spi/BackendService.getApiConfigs HTTP/1.1" 200 329507
INFO     2016-02-24 19:25:55,894 data_access.py:354] (u'CLIN:gender', True)
INFO     2016-02-24 19:25:55,895 data_access.py:354] (u'CLIN:histological_type', True)
INFO     2016-02-24 19:25:55,896 data_access.py:354] (u'CLIN:histological_type', True)
Called authorize_credentials_with_Google
 big query authorization authorize_credentials_with_Google
INFO     2016-02-24 19:25:55,921 discovery.py:810] URL being requested: POST https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs?alt=json
INFO     2016-02-24 19:25:55,922 client.py:563] Attempting refresh to obtain initial access_token
INFO     2016-02-24 19:25:55,955 client.py:865] Refreshing access_token
WARNING  2016-02-24 19:25:56,338 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:25:57,332 utils.py:120] FEATURE BQ_SUBMIT TIME 1.42154693604
INFO     2016-02-24 19:25:57,333 data_access.py:170] Submitted TCGA job_xKRBJiWv8tjNR2kYj77JK19kOkg: CLIN:gender - [3, 2]
INFO     2016-02-24 19:25:57,341 discovery.py:810] URL being requested: POST https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs?alt=json
WARNING  2016-02-24 19:25:57,343 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:25:58,048 utils.py:120] FEATURE BQ_SUBMIT TIME 0.71177983284
INFO     2016-02-24 19:25:58,049 data_access.py:170] Submitted TCGA job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ: CLIN:histological_type - [3, 2]
INFO     2016-02-24 19:25:58,056 discovery.py:810] URL being requested: POST https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs?alt=json
WARNING  2016-02-24 19:25:58,059 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:25:58,762 utils.py:120] FEATURE BQ_SUBMIT TIME 0.709463119507
INFO     2016-02-24 19:25:58,762 data_access.py:170] Submitted TCGA job_Y3LXB36Sr-6yAKrL0naz8glb4HA: CLIN:histological_type - [3, 2]
INFO     2016-02-24 19:25:58,765 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_xKRBJiWv8tjNR2kYj77JK19kOkg?alt=json
WARNING  2016-02-24 19:25:58,779 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:25:59,349 data_access.py:214] Status job_xKRBJiWv8tjNR2kYj77JK19kOkg: False
INFO     2016-02-24 19:26:00,353 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ?alt=json
WARNING  2016-02-24 19:26:00,366 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:00,957 data_access.py:214] Status job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ: False
INFO     2016-02-24 19:26:01,962 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_Y3LXB36Sr-6yAKrL0naz8glb4HA?alt=json
WARNING  2016-02-24 19:26:01,971 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:02,597 data_access.py:214] Status job_Y3LXB36Sr-6yAKrL0naz8glb4HA: True
INFO     2016-02-24 19:26:02,600 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/lsdf-cgc/queries/job_Y3LXB36Sr-6yAKrL0naz8glb4HA?alt=json
WARNING  2016-02-24 19:26:02,612 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:04,464 utils.py:120] FEATURE BQ_FETCH TIME 1.86687016487
INFO     2016-02-24 19:26:04,558 utils.py:120] CLIN UNPACK TIME 0.0927169322968
INFO     2016-02-24 19:26:05,587 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_xKRBJiWv8tjNR2kYj77JK19kOkg?alt=json
WARNING  2016-02-24 19:26:05,598 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:06,254 data_access.py:214] Status job_xKRBJiWv8tjNR2kYj77JK19kOkg: True
INFO     2016-02-24 19:26:06,257 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/lsdf-cgc/queries/job_xKRBJiWv8tjNR2kYj77JK19kOkg?alt=json
WARNING  2016-02-24 19:26:06,267 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:08,113 utils.py:120] FEATURE BQ_FETCH TIME 1.85819602013
INFO     2016-02-24 19:26:08,142 utils.py:120] CLIN UNPACK TIME 0.0293989181519
INFO     2016-02-24 19:26:09,172 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ?alt=json
WARNING  2016-02-24 19:26:09,182 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:09,796 data_access.py:214] Status job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ: True
INFO     2016-02-24 19:26:09,798 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/lsdf-cgc/queries/job_O9FMSnVlkE_ezGwt5lFDBWKfNcQ?alt=json
WARNING  2016-02-24 19:26:09,803 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:11,415 utils.py:120] FEATURE BQ_FETCH TIME 1.61940717697
INFO     2016-02-24 19:26:11,454 utils.py:120] CLIN UNPACK TIME 0.038449048996
INFO     2016-02-24 19:26:12,489 discovery.py:810] URL being requested: GET https://www.googleapis.com/bigquery/v2/projects/290313091846/jobs/job_Y3LXB36Sr-6yAKrL0naz8glb4HA?alt=json
WARNING  2016-02-24 19:26:12,500 urlfetch_stub.py:540] Stripped prohibited headers from URLFetch request: ['content-length']
INFO     2016-02-24 19:26:13,068 data_access.py:214] Status job_Y3LXB36Sr-6yAKrL0naz8glb4HA: True
INFO     2016-02-24 19:26:14,327 utils.py:120] FEATURE VECTOR_MERGE TIME 0.0331289768219
ERROR    2016-02-24 19:26:15,134 urlfetch_stub.py:221] Invalid protocol: 
ERROR    2016-02-24 19:26:15,142 pairwise.py:138] cannot concatenate 'str' and 'NoneType' objects
Traceback (most recent call last):
  File "/home/vagrant/www/api/pairwise.py", line 135, in run_pairwise
    pairwise_response = urlfetch.fetch(url=url, payload=data, method=urlfetch.POST)
  File "/home/vagrant/google_appengine/google/appengine/api/urlfetch.py", line 271, in fetch
    return rpc.get_result()
  File "/home/vagrant/google_appengine/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/home/vagrant/google_appengine/google/appengine/api/urlfetch.py", line 389, in _get_fetch_result
    'Invalid request URL: ' + url + error_detail)
TypeError: cannot concatenate 'str' and 'NoneType' objects
WARNING  2016-02-24 19:26:15,147 data_access.py:310] Pairwise results not included in returned object
ERROR    2016-02-24 19:26:15,147 data_access.py:311] 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/home/vagrant/www/api/data_access.py", line 308, in get_merged_feature_vectors
    pairwise_result = self.get_pairwise_result(input_vectors)
  File "/home/vagrant/www/bq_data_access/utils.py", line 125, in wrapped_function
    result = f(_args, *_kwargs)
  File "/home/vagrant/www/api/data_access.py", line 171, in get_pairwise_result
    for row_label, row in outputs.items():
AttributeError: 'NoneType' object has no attribute 'items'
INFO     2016-02-24 19:26:15,172 utils.py:120] FEATURE GET_VECTORS TIME 19.2759749889
INFO     2016-02-24 19:26:16,114 module.py:786] mvm: "POST /_ah/spi/FeatureDataEndpoints.data_access_for_plot HTTP/1.1" 200 3070954
INFO     2016-02-24 19:26:16,535 module.py:786] mvm: "GET /_ah/api/feature_data_api/v1/feature_data_plot?cohort_id=3&cohort_id=2&x_id=CLIN:gender&c_id=CLIN:histological_type&y_id=CLIN:histological_type HTTP/1.1" 200 3590021

**Comment by phyllers** [comment]
Okay, so testing locally, I get a DeadlineExceededError. I'm guessing you don't have the PAIRWISE_SERVICE_URL in your settings? This is a service we're running on a vm in our project to calculate pairwise results. Perhaps we should put in a check, if it isn't in the settings, then don't try to calculate the pairwise. Then a check in the template for it?

**Comment by rgbohner** [comment]
I added the pairwise service url in the setting and that seems to do the trick
