### ISSUE TITLE
Variable list does not expand while clicking "more" in Data Source | Variables

### ISSUE THREAD

**Issue by kleisb** [BlinkUX/ISB-CGC#161]
Hovering over or clicking the `8 more` tag below `C Samp Pam Call` does not do anything. 

![data_source_variables](https://cloud.githubusercontent.com/assets/2643103/13302708/331bbbba-db00-11e5-816d-119fabb0e49d.png)

**Comment by rgbohner** [comment]
This was accidently committed to the LSDF cgc-master branch instead of its own branch.  I will be submitting a pull request on the cgc-master for this issue
