### ISSUE TITLE
Analysis view queries for wrong cohort for scatter plot

### ISSUE THREAD

**Issue by kleisb** [BlinkUX/ISB-CGC#162]
While drawing the scatter plot, web client queries the plot data endpoint with cohort identifier. See attached screenshot for analysis settings. Cohort `5` is union of `3` and `4`.

Query URI from client (from Chrome debugger and application log):

```
/_ah/api/feature_data_api/v1/feature_data_plot?cohort_id=3&x_id=USER:4:7&c_id=USER:4:12&y_id=USER:1:1
```

Manually changing the cohort id to `5` returns the correct data (sample IDs starting with `GTEX` and `TCGA` are present):

```
/_ah/api/feature_data_api/v1/feature_data_plot?cohort_id=5&x_id=USER:4:7&c_id=USER:4:12&y_id=USER:1:1
```

MySQL log:

```
mysql> select * from cohorts_cohort;
+----+---------------------+--------+---------------------+
| id | name                | active | last_date_saved     |
+----+---------------------+--------+---------------------+
|  1 | All TCGA Data       |      1 | 2016-02-23 19:13:36 |
|  2 | Brain               |      1 | 2016-02-23 23:44:31 |
|  3 | GTEx                |      1 | 2016-02-24 00:25:37 |
|  4 | BRCA_820_PAM50      |      1 | 2016-02-24 02:29:11 |
|  5 | GTEx+BRCA_280_PAM50 |      1 | 2016-02-24 22:01:23 |
+----+---------------------+--------+---------------------+
```

![analysis_settings](https://cloud.githubusercontent.com/assets/2643103/13303564/fdb21ec4-db04-11e5-9120-f6be5c8f4b59.png)

**Comment by phyllers** [comment]
Ross has made some changes to how cohort selection is done. Please pull from master to see if that fixes it.

Otherwise, is there an issue with data being returned?

**Comment by kleisb** [comment]
@phyllers The wrong cohort ID issue was fixed.
