### ISSUE TITLE
Can no longer view cohort list page

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#165]
![screen shot 2016-02-24 at 5 49 10 pm](https://cloud.githubusercontent.com/assets/4040084/13307270/f14905a2-db1e-11e5-9ddf-e54f7629d074.png)

**Comment by phyllers** [comment]
![screen shot 2016-02-24 at 5 49 38 pm](https://cloud.githubusercontent.com/assets/4040084/13307276/fe937332-db1e-11e5-9c07-865fecba0e51.png)

I think the previous fix of setting the bool to `not create_workbook` broke it.

**Comment by rgbohner** [comment]
referencing #127
