### ISSUE TITLE
Cannot view workbook that was shared with me

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#175]
<img width="847" alt="screen shot 2016-02-25 at 6 54 18 pm" src="https://cloud.githubusercontent.com/assets/4040084/13341874/3c825942-dbf1-11e5-950a-94ad1deae11e.png">

This might be related to #150?

**Comment by rgbohner** [comment]
I believe it is related to 150 but is a different issue.  Can you list the actions to recreate this issue?

**Comment by phyllers** [comment]
I share a workbook using one user account, then when I click on the link in the email, I get this error page.

But when I log in normally, I can see it in my workbooks.

**Comment by rgbohner** [comment]
Can you share it with me so I can take a look

**Comment by phyllers** [comment]
Shared. also, the share button doesn't appear right away. I have to edit it and then it appears.   This was caused by issue #177
