### ISSUE TITLE
new workbook button does not work in the projects page

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#179]

**Comment by phyllers** [comment]
The delete project button is also inoperable.

**Comment by phyllers** [comment]
We want a modal to appear for project delete, correct?

**Comment by rgbohner** [comment]
Correct

**Comment by phyllers** [comment]
Okie dokie:

https://github.com/isb-cgc/ISB-CGC-Webapp/commit/f7ba620af7e7509a355e8248c30a954c03c7d2ed

**Comment by rgbohner** [comment]
I am not seeing this working.  Are you looking at the project list page or the project details page?

**Comment by phyllers** [comment]
It was from the project list page.

**Comment by phyllers** [comment]
Oh i see, it's broken in the project details page too. Fix coming up.

**Comment by rgbohner** [comment]
Ah, okay, There is still the issue of the new workbook button not working on the project details page

**Comment by phyllers** [comment]
https://github.com/isb-cgc/ISB-CGC-Webapp/commit/3a59539fff9250827885553b556cd38890d9725c
