### ISSUE TITLE
Scatterplots producing insane amount of errors

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#187]
![image](https://cloud.githubusercontent.com/assets/2424291/13366099/007cc278-dc8e-11e5-9338-45d49534c7fb.png)

It appears there needs to be checks for missing data

**Comment by phyllers** [comment]
i think this is fixed now.

**Comment by rgbohner** [comment]
There seems to be possibly another issue with the scatterplot, 
![image](https://cloud.githubusercontent.com/assets/2424291/13374981/f0483926-dd48-11e5-8c31-db338953da80.png)

I can reproduce it easily with one my plots, so I'll make the quick fix
