### ISSUE TITLE
Adding action buttons to the dashboard

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#197]
Per the request from Brady, add create buttons to the dashboard lists

**Comment by phyllers** [comment]
![screen shot 2016-03-02 at 1 01 42 pm](https://cloud.githubusercontent.com/assets/4040084/13475307/f31f550e-e076-11e5-82b2-f27a9be28fd7.png)

What should it look like if there are more than 6 things?

**Comment by phyllers** [comment]
i pulled the view all to the right.
