### ISSUE TITLE
Cohorts are not viewable on staging

### ISSUE THREAD

**Issue by LoveAndCoding** [BlinkUX/ISB-CGC#20]
Looks like it may be a dependency issue? Endpoint seems to be having some trouble

**Comment by phyllers** [comment]
We have been making _lots_ of changes to our endpoints in the past little while. It may be a good idea to pull in those changes.

**Comment by LoveAndCoding** [comment]
Alright, thanks. I'll try that and see if that fixes the issue

**Comment by LoveAndCoding** [comment]
Fix incoming. Will test on staging once it deploys
