### ISSUE TITLE
Disabled tab on upload data page is not styled differently

### ISSUE THREAD

**Issue by LoveAndCoding** [BlinkUX/ISB-CGC#27]
We should probably style the tab selection differently on the upload data page if the from existing project is disabled. Minor thing. Already not clickable and should have the `.disabled` class added to it.

Happens when the user has no projects to select from

**Comment by LoveAndCoding** [comment]
I would put this as low priority and I can tackle it if you would like. Mostly just tracking it. Bounce it to me if you'd prefer I just tweak it 'cause I know you got a lot on your plate.

**Comment by litopia** [comment]
I can do it. I was giving it a different style. For some reasons, it didn't get picked up.
