### ISSUE TITLE
Cohorts not appearing in Dashboard Card

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#52]
I created a cohort through a workbook, but the dashboard says that I have no cohorts. The menu says that I have one.

When I click on that, it takes me to my cohort and I can also see the public TCGA cohort. Until then, I have no idea, that the TCGA cohort existed... O_o

**Comment by LoveAndCoding** [comment]
This has to do with using last viewed instead of just using the list of cohorts. This will be easier to fix once sharing gets ported over as part of the sharing changes in the next couple days. Will make this part of that work.

**Comment by litopia** [comment]
This issue is also applied to the site navigation's public cohorts and public projects, can you take a look at that as well?

**Comment by LoveAndCoding** [comment]
Fixed in sharing branch

**Comment by LoveAndCoding** [comment]
Merged into master and into pull request. Closing
