### ISSUE TITLE
Menu open and page push down are animated differently

### ISSUE THREAD

**Issue by LoveAndCoding** [BlinkUX/ISB-CGC#7]
It looks like the Menu open animation is using a linear animation but the page push down is using a swing animation style or something. Is this intentional?

**Comment by litopia** [comment]
Not too intentional. Mainly it is because the menu toggle is from Bootstrap's built-in animation using ease-in-out and the page push was added later. I like the inconsistency of it, so I didn't make them consistent.

**Comment by LoveAndCoding** [comment]
Fair enough. Doesn't make much of a difference to me, but I noticed it so I thought I'd see if it was intentional :)
