### ISSUE TITLE
Create data dictionary hyperlinks for gene selection page

### ISSUE THREAD

**Issue by rgbohner** [BlinkUX/ISB-CGC#72]

**Comment by rgbohner** [comment]
The designs do not have this page.  Does your team have this page for us to reference?

**Comment by rgbohner** [comment]
For now the hyperlink to data dictionary page on the gene pages has been disabled

**Comment by phyllers** [comment]
No Problem. I can't even remember what it was supposed to be. Sorry!

**Comment by rgbohner** [comment]
Shall we close this issue then?

**Comment by phyllers** [comment]
I think it's safe to close it. I will add it to our own issue tracker as a future feature.

**Comment by rgbohner** [comment]
Right now the  data dictionary is listed in the data upload page, should we remove this link as well? 

<img width="670" alt="dictionary" src="https://cloud.githubusercontent.com/assets/2424291/12801150/33b30ca8-ca8f-11e5-87b9-a246820503b4.png">

**Comment by rgbohner** [comment]
There is a data dictionary list in the data_upload.js file.  We can create an html view of that json hash.  This might suffice for having a page listing the data dictionary.

**Comment by phyllers** [comment]
If it can be easily done, then make it so. :)

**Comment by phyllers** [comment]
Link has been put in for gene list, will wait for documentation to be complete for system variables
