### ISSUE TITLE
Gene list creation workflow from workbook

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#80]
From my workflow, I tried select Genes and didn't have any lists created, so I clicks "+ Apply New Gene List"

That took me to this page:

<img width="1204" alt="screen shot 2016-01-05 at 12 28 33 pm" src="https://cloud.githubusercontent.com/assets/4040084/12126874/bb95fe12-b3a8-11e5-8cb0-f78bca4aae7f.png">

But if I hit cancel, it takes me here:

<img width="1200" alt="screen shot 2016-01-05 at 12 28 43 pm" src="https://cloud.githubusercontent.com/assets/4040084/12126892/c7ee9caa-b3a8-11e5-91b0-ef8b89fe6518.png">

Where I would have expected it to take me back to my workbook, or at least still see it in the breadcrumbs. 

It also wouldn't let me Apply TP53 to my workbook.

**Comment by rgbohner** [comment]
Yep the cancel is routing to the wrong url in genes, I'll patch in next update
