### ISSUE TITLE
Dashboard doesn't load if I've created a gene favourite

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#82]
<img width="1149" alt="screen shot 2016-01-05 at 4 01 40 pm" src="https://cloud.githubusercontent.com/assets/4040084/12131236/b6c27c36-b3c5-11e5-95b2-94c94e50a3c7.png">

I have one gene favourite. I suspect the url should be 'gene_fav_detail' perhaps?

**Comment by rgbohner** [comment]
Fixed in latest merge to Blink master : https://github.com/BlinkUX/ISB-CGC/commit/c2b42bedbdb79705b7e20019bf648911c49b0aef
