### ISSUE TITLE
Plots on new cohort page don't update properly

### ISSUE THREAD

**Issue by LoveAndCoding** [BlinkUX/ISB-CGC#95]
The API has been updated to properly filter counts based on the filters applied, but it does not look like those are getting transferred to the plots on the main area of the page.

**Comment by rgbohner** [comment]
Can you elaborate on this.  What plots are you referring to?

**Comment by LoveAndCoding** [comment]
![ISB Cohort Plots](https://cloud.githubusercontent.com/assets/205630/12520032/0f4b859e-c0f7-11e5-9dfe-e39b35dc6aad.png)

These (currently) blue plots are the ones not being updated. They are pulled from the API which should be working and updated but these plots always seem to return undefined. Maybe a change in the format of the return or something?

**Comment by phyllers** [comment]
Locally, I can see that all the counts returned are 0.

**Comment by phyllers** [comment]
I have plots rendering correctly on load, but when I select any filter, the results of the metadata_counts api call is 0 for everything. 

Also, the filters themselves don't update their counts, and the results render only blank squares for the mosaic plots.

**Comment by phyllers** [comment]
Fixed this in the metadata_counts endpoint. Addressed in this [commit](https://github.com/isb-cgc/ISB-CGC-Webapp/commit/5b80145faecc6628daa856009b9c4850a692c315)
