### ISSUE TITLE
Secondary nav bar on request project page misaligned

### ISSUE THREAD

**Issue by phyllers** [BlinkUX/ISB-CGC#99]
<img width="1680" alt="screen shot 2016-01-19 at 2 07 04 pm" src="https://cloud.githubusercontent.com/assets/4040084/12433454/04ca0f02-beb6-11e5-8ced-44a20e7a1397.png">

**Comment by rgbohner** [comment]
Only if requesting a project

**Comment by phyllers** [comment]
hurray!
